Next v0.4.0 release
meilisearch/strapi-plugin-meilisearch pull request #301
Opened 2021-11-03 17:41 UTC by jbelke

Update Batch Size to Eliminate SQL Error SQLITE_ERROR: too many SQL variables

2021-11-03 17:46 UTC, bidoubiwa requested changes

2021-11-03 17:46 UTC, bidoubiwa commented on .github/dependabot.yml
> +      - dependency-name: "*concurrently*"
```suggestion
      - dependency-name: "*eslint*"
      - dependency-name: "*prettier*"
```

2021-11-03 17:46 UTC, bidoubiwa commented on .github/dependabot.yml
> +      - dependency-name: "*prettier*"
```suggestion
      - dependency-name: "*eslint*"
```

2021-11-04 14:30 UTC, bidoubiwa commented
Dependabot file is still present in the files changed, could you remove the file from the PR?

2021-11-08 22:33 UTC, jbelke reviewed
Approved

2021-11-08 22:44 UTC, bidoubiwa approved these changes
LGTM 🔥 Thnks a lot

2021-11-08 22:44 UTC, bidoubiwa commented
bors merge

2021-11-08 22:47 UTC, merged