Implement language translations for handling multi-language plugin
meilisearch/strapi-plugin-meilisearch pull request #915
Opened 2024-04-04 02:21 UTC by mimartinez

# Pull Request

## Related issue
Fixes #85

## What does this PR do?
- Implement language translations for handling multi-language plugin
- Added translation files `en.json` and `es.json`

## PR checklist
Please check if your PR fulfills the following requirements:
- [x] Does this PR fix an existing issue, or have you listed the changes applied in the PR description (and why they are needed)?
- [x] Have you read the contributing guidelines?
- [x] Have you made sure that the title is accurate and descriptive of the changes?

Thank you so much for contributing to Meilisearch!

2024-04-04 18:10 UTC, brunoocasali requested changes
Heey @mimartinez thanks a lot for this PR!

I put some comments, lets discuss them, after that I will merge it :)

Thanks a lot!

2024-04-04 20:34 UTC, mimartinez commented on admin/src/containers/Settings/Credentials.js
> +            'Meilisearch Host',
It was already like that, so I didn't touch it 😉. But you're right, we changed it 👍

2024-04-04 20:56 UTC, mimartinez commented on admin/src/utils/getTrad.js
> +export default getTrad
It is also used in the `useI18n.js` hook. But you can remove it and do the same in the hook which is what is called everywhere 👌

2024-04-04 21:57 UTC, mimartinez commented on admin/src/index.js
> +    return Promise.resolve(importedTrads)
This is the example they have in Strapi Doc for plugin development https://docs.strapi.io/dev-docs/api/plugins/admin-panel-api#registertrads

2024-04-04 22:04 UTC, mimartinez commented on admin/src/index.js
> +    return Promise.resolve(importedTrads)
It is true that the second `Promise.all` is not necessary. I have left it as the example in Strapi's documentation.

2024-04-19 17:52 UTC, mimartinez commented
Hi @brunoocasali,
Is there a problem with this PR, can I help? 
Regards

2024-04-22 12:29 UTC, curquiza commented
Hello @mimartinez 

@brunoocasali is still on Holiday and will review when he'll come back

2024-05-16 18:19 UTC, brunoocasali approved these changes
Amazing work here @mimartinez 🎉 

bors merge

2024-05-16 18:21 UTC, merged